runtime: go112  # or go113 for Go 1.13 runtime (beta)

instance_class: F2
env: standard
env_variables:
  PROJECT_ID: "covid19-273910"
  TOKEN: "904642129:AAHsIMNgVTUyjPDsfMAj8EI22ECW4bBevkY"
  URL: ""
  PORT: "8080"
  REDIS_URL: "localhost:6379"
  REDIS_PASSWORD: ""
  ENV : "local"



automatic_scaling:
    max_instances: 1

handlers:
- url : .*
  script: auto
  secure: always
